name: "Docker Tags Action"
author: "Dominik Nakamura"
description: "Generate tags for Docker images based on the current ref-spec"
inputs:
  registries:
    description: "Space separated list of registries"
    required: false
    default: "docker.io"
outputs:
  tags:
    description: "All tags that should be set on a Docker image"
branding:
  icon: "tag"
  color: "blue"
runs:
  using: "docker"
  image: "docker://ghcr.io/dnaka91/action-docker-tags:0.2.0"
  args:
    - ${{ inputs.registries }}
